version: '3.9'

services:
  kong:
    image: kong/kong-gateway:3.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
    ports:
      - target: 8000
        published: 8000
        mode: host
      - target: 8443
        published: 8443
        mode: host
      - target: 8001
        published: 8001
        mode: host
      - target: 8444
        published: 8444
        mode: host
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml

  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger

  messenger:
    image: ghcr.io/fullstack1o1/messenger:main
    restart: on-failure
    depends_on:
      - "db"
    ports:
      - target: 8080
        published: 8080
        mode: ingress
    environment:
      spring.datasource.url: 'jdbc:postgresql://db:5432/messenger'
      spring.datasource.username: 'admin'
      spring.datasource.password: 'password'
      spring.flyway.enabled: 'true'
    deploy:
      replicas: 2
      mode: replicated
      update_config:
        order: stop-first
      resources:
        limits:
          cpus: '0.50'
          memory: 700M
        reservations:
          cpus: '0.25'
          memory: 100M
