@HOST=http://localhost:8080
@EXAMPLE_USERNAME=Alice
@EXAMPLE_ACCESS_KEY=password


### new group
POST {{HOST}}/group
Accept: application/json
Content-Type: application/json
Authorization: Basic {{EXAMPLE_USERNAME}} {{EXAMPLE_ACCESS_KEY}}

{
  "groupName": "rock911",
  "members": [
    {
      "userId": 2
    }
  ]
}


### fetch loggedIn user group
GET {{HOST}}/group
Authorization: Basic {{EXAMPLE_USERNAME}} {{EXAMPLE_ACCESS_KEY}}
Accept: application/json

###
GET {{HOST}}/group
Authorization: Basic Bob {{EXAMPLE_ACCESS_KEY}}
Accept: application/json

###
PATCH {{HOST}}/group/1
Accept: application/json
Content-Type: application/json
Authorization: Basic {{EXAMPLE_USERNAME}} {{EXAMPLE_ACCESS_KEY}}

{
  "members": [
    {
      "userId": 3
    }
  ]
}

###
GET {{HOST}}/group
Authorization: Basic Charlie {{EXAMPLE_ACCESS_KEY}}
Accept: application/json

### group messages
GET {{HOST}}/group/1/messages
Authorization: Basic Charlie {{EXAMPLE_ACCESS_KEY}}
Accept: application/json